#!/bin/bash

uninstall=false
install=true
quiet=false

# Parse command-line arguments
for arg in "$@"; do
    case $arg in
        --uninstall)
        uninstall=true
        install=false
        ;;
        --reinstall)
        uninstall=true
        install=true
        ;;
        --quiet-on-do-nothing)
        quiet=true
        ;;
    esac
done

# Uninstall Poetry if --uninstall or --reinstall flag is provided
if [ "$uninstall" = true ]; then
    echo "Uninstalling Poetry..."
    curl -sSL https://install.python-poetry.org | python3 - --uninstall
    rm -rf ~/Library/Application\ Support/pypoetry 2>/dev/null
fi

# Check if Poetry is installed using 'which'
if ! which poetry &> /dev/null; then
    echo "Installing Poetry..."
    curl -sSL https://install.python-poetry.org | python3 -
    add-to-path "$HOME/.local/bin"
else
    if [ "$quiet" = false ]; then
        echo "Poetry is already installed. To reinstall, call 'install-poetry --reinstall'"
    fi
fi
