#!/bin/bash

# Function to check if a package is installed
is_package_installed() {
    if python --no-poetry -m pip show "$1" > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}


# Check for --no-upgrade flag and if aider-chat is already installed
if [[ "$1" == "--no-upgrade" ]]; then
    if is_package_installed "aider-chat"; then
        exit 0
    fi
fi

# Install universal-ctags
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-get install universal-ctags
elif [[ "$OSTYPE" == "darwin"* ]]; then
    brew install --HEAD universal-ctags/universal-ctags/universal-ctags
else
    echo "Unsupported operating system"
    exit 1
fi

# Install or upgrade aider-chat using pip
if is_package_installed "aider-chat"; then
    python -m pip install aider-chat --upgrade
else
    python -m pip install aider-chat
fi
