#!/bin/bash

# Check if an argument is provided
if [ "$#" -ne 1 ]; then
  echo "Usage: mc <command_name>"
  exit 1
fi

command_name="$(check-alias $1)"
script_dir=$(dirname "$0")
command_path="$script_dir/$command_name"

# Check if the command exists in /usr/local/bin
if [ -f "$command_path" ]; then
  # If it exists, open it in vim
  vim "$command_path"
else
  # If it does not exist, create a new file with the basic template
  echo "#!/bin/bash" > "$command_path"

  # Open the file in vim
  vim "$command_path"

  # Check if the file has more than 1 line
  if [ "$(wc -l < "$command_path")" -gt 1 ]; then
    # If it does, make the file executable
    chmod +x "$command_path"
  else
    # If it does not, delete the file
    rm "$command_path"
  fi
fi
