[tool.poetry]
name = "code-chat"
version = "0.1.0"
description = ""
authors = ["Sam Haaf <samhaaf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
kit = {path = "../kit"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
